GET localhost:8080/meal
Content-Type: application/json

####

GET localhost:8080/meal/m1
Content-Type: application/json

####

POST localhost:8080/meal
Content-Type: application/json

{
  "mealId": "m5",
  "mealName": "Bulgogi",
  "description": "Korean, traditional",
  "mealPrice": 20
}

####

PUT localhost:8080/meal
Content-Type: application/json

{
  "mealId": "m4",
  "mealName": "Green Bowl",
  "description": "Healthy...and green...",
  "mealPrice": 18.99,
  "imagePath": "src/file/GreenBowl.jpg"
}